Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '1.5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 377, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 434, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 535, in parse_int
    return parse_int(v[:-1], keywords) * multiplier
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 539, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 1.5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 1: Invalid field value 1.5
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '1.5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 377, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 434, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 535, in parse_int
    return parse_int(v[:-1], keywords) * multiplier
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 539, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 1.5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 1: Invalid field value 1.5
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '1.5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 377, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 434, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 535, in parse_int
    return parse_int(v[:-1], keywords) * multiplier
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 539, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 1.5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 1: Invalid field value 1.5
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '1.5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 377, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 434, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 535, in parse_int
    return parse_int(v[:-1], keywords) * multiplier
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 539, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 1.5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 1: Invalid field value 1.5
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '1.5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 377, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 434, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 535, in parse_int
    return parse_int(v[:-1], keywords) * multiplier
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 539, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 1.5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\coler\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 1: Invalid field value 1.5
Please check extra_partition_subtypes.inc file in build/config directory
